### ISSUE TITLE
Ховеры

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#1]
Не реализованы ховеры по:
- Пунктам меню
- Фиолетовым кнопкам
- "Кривых" кнопках. Обрати внимание, что рамка на ней с прозрачностью `50%`, а в состоянии наведения `100%`
- Элементы услуг на главной

Сверь ховеры в вкладке UI

**Comment by RamizAshurov** [comment]
Ховеры добавил. У "кривых кнопках" в UI рамка стоит с прозрачностью 20%, а в макете - с прозрачностью 50%. Оставил 50%

**Comment by RamizAshurov** [comment]
Ховеры добавил. У "кривых кнопках" в UI рамка стоит с прозрачностью 20%, а в макете - с прозрачностью 50%. Оставил 50%

**Comment by RamizAshurov** [comment]
- Добавил ховер кнопкам меню
- Добавил ховер фиолетовым кнопкам
- Поменял прозрачноть рамок у кривых кнопок
- Добавил ховер элементам услуг
