### ISSUE TITLE
Футер

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#10]
1. Логотип "акцент на результат" должен быть ссылкой на `https://aaccent.ru`
2. "Политика конфиденциальности и условия..." должно быть ссылкой
3. "Все права защищены" в одну строку
4. Между логотипом компании и "Следите за нами" должно бы расстояние

**Comment by RamizAshurov** [comment]
- Логотип сделал ссылкой. Ссылка открывается в новой вкладке
- "Политика конфиденциальности и условия..." сделал ссылкой. Ссылка открывается в новой вкладке
- "Все права защищены" в одну строку. Добавил символы &nbsp;
- Добавил расстояние между логотипом и "Следите за нами"

**Comment by foxhable** [comment]
В две строки в верстке, в макете она в одну строку

![image](https://github.com/aaccent/med-tourism/assets/36298346/c89def61-48d4-4c10-8b0c-e1a6bd363fdd)

**Comment by RamizAshurov** [comment]
Исправил
