### ISSUE TITLE
Разметка контентных страниц

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#11]
На страницах

"О компании"
"Услуга"

Нужно изменить разметку, т.к. контент менеджеры не всегда достаточно квалифицированы или внимательны.

### Правила
- Контент нужно разместить в единый контейнер. Например:
```html
<h1 class="page__title-h1">О Компании</h1>
<div class="page__content">
  <p>Наша компания сотрудничает с опытными</p>
  <h2>Внутренний заголовок страницы H2</h2>
</div>
```
- Не должно быть атрибутов `class`, `id`, `data-*`. Любая стилизация происходит с помощью контейнера:
```css
.page__content p {}
.page__content h2 {}
```
- Цитаты должны быть в `blockquote` тэге
- Расстояния между блоками нужно делать с помощью `margin-top` на `h*` тэгах вместо использования `page__block`

**Comment by RamizAshurov** [comment]
- Весь контент поместил в контейнер
- Классы оставил только у тегов p, у них в макете переменная ширина, и контейнере тега img для стилизации
- Цитату поместил в тег blockquote
- Убрал класс page__block, задал вертикальные отступы тегам h* и p

**Comment by foxhable** [comment]
Не, прям ноль классов должно быть в контенте, я blockquote попросил, потому что название тэга вместо класса можно использовать. Всё, что находится в контенте это вносится вручную КМами, даже если они квалифицированы, то им неудобно делать разметку с классами. У них десятки сайтов, если на каждом будут какие-то особые классы или глубокая вложенность, то это усложнение работы

![image](https://github.com/aaccent/med-tourism/assets/36298346/072ea3c6-ae4a-4805-b8d9-566b082d86eb)

![image](https://github.com/aaccent/med-tourism/assets/36298346/737ab0b8-002f-42d6-aec4-d04792d0ebcd)

**Comment by RamizAshurov** [comment]
Исправил

**Comment by foxhable** [comment]
Последние два момента по этой проблеме:
Не 
```html
<p class="page__desc">...</p>
```
а
```html
<div class="page__desc">
  <p>...</p>
</div>
```

---

На странице услуги тоже убери оставшиеся классы, чтобы сборщик не путался

**Comment by RamizAshurov** [comment]
Исправил
