### ISSUE TITLE
Метка на карте

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#13]
Метка и центр на карте должнг устанавливаться через `data-*` атрибут. Это необходимо, чтобы сборщик выводил метку из админки в разметку.

Не должно быть такого хардкода в js.
https://github.com/aaccent/med-tourism/blob/0418553a124947d052a89ac5328d939c90390511/src/js/app.js#L183

Это должно выглядеть примерно так:
```html
<div id="map" data-mark="55.7954692462696,49.10686513125719"></div>
```

```js
const map = document.querySelector('#map')
const coords = map?.dataset.mark?.split(',').map(Number) || [55.7954692462696,49.10686513125719]
```

**Comment by RamizAshurov** [comment]
Вынес координаты центра и метки в дата атрибуты
