### ISSUE TITLE
Список клиник

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#14]
Расстояние под заголовком больше макета

**Comment by RamizAshurov** [comment]
Исправил

**Comment by foxhable** [comment]
У тебя на `.clinic__content` есть верхний паддинг, из-за чего к паддингу от `.clinics__item.clinic` добавляется `55px` сверху

<details><summary>Скрин</summary>

![Uploading image.png…]()
</details>

**Comment by RamizAshurov** [comment]
Скрин не грузится. На ширине 1920 и выше отступ  такой же как в макете, так как отступ отсчитывается от картинки клиники. На ширине ниже 1920 картинка уменьшается и визуально добавляется отступ от .clinic__content

**Comment by foxhable** [comment]
Контент добавляет паддинг сверху. Я смотрю на 1920

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/39ed6641-b77f-4b40-8612-d289accd1e1e)
</details> 

и получается отступ больше, чем на макете

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/13acccf2-1ac6-46a7-8e0c-95471ceb3ab1)
</details> 

Нужно картинку не по центру текста выравнивать, а по верхнему краю, иначе если добавить параграф текста - будет это

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/28e7556a-c674-440f-b2e7-e120dcf70b3a)
</details>

**Comment by RamizAshurov** [comment]
Выровнил картинку
