### ISSUE TITLE
Страница контактов

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#15]
1. Прикрепить файл не от центрован по иконке
2. Иконка прикрепления должна быть 24х24, в верстке 40х40
3. Кнопка "Получить консультацию" должна быть под "Прикрепить файл"
4. Текст о политике должен быть полупрозрачным и от центрован по левому краю

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/460edef8-c117-499e-ac9b-64e714cb7ed7)
</details> 

<br/>

5. Переносы должны соответствовать макету

<details><summary>Сравнение</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/9db414a6-1833-491a-8ce8-60322fd865ac)
</details> 

<br/>

7. Если прикрепить файл с слишком длинным названием, то все пойдет не так

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/1baa5e88-f08e-4593-98e5-550f6f54706f)
</details> 

<br/>

8. Между блоком с картой и футером должно быть расстояние

**Comment by RamizAshurov** [comment]
1. Отцентрировал иконку и поменял размеры
2. Поменял местами кнопку "Получить консулттацию" с "Прикрепить файл"
3. Выровнил текст о политике по левому краю и добавил прозрачность
4. Исправил переносы
5. Откорректировал  ширину контейнера с именем прикрепленного файла
6. Добавил отступ между футером и картой

**Comment by foxhable** [comment]
Иконка крестика меньше, чем в макете

**Comment by RamizAshurov** [comment]
Исправил размер иконки
