### ISSUE TITLE
Хлебные крошки мобилка

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#16]
1. На самом минимальном разрешении шапка перекрывает крошки

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/7d58ba4c-b222-45c7-91a8-535c5d475e77)
</details> 

---

2. Между крошками и заголовком страницы должно быть `20px`

<details><summary>Скрин</summary>

![Uploading image.png…]()
</details>

**Comment by RamizAshurov** [comment]
1. Наложение шапки на крошки убрал
2. Отступы проверил: по макету на мобилках 10px, на десктопе - 20px
