### ISSUE TITLE
Мобильное меню

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#17]
1. Иконка у текста "Услуги" в макете 18х18, в верстке 24х24

![image](https://github.com/aaccent/med-tourism/assets/36298346/c6dc35cb-b3b6-4155-80f6-a57af9fb9a38)

---

2. При нажатии на "Записаться на прием" попап открывается под меню и его не видно

---

3. У кнопки "Заказать звонок" не должно быть иконки

**Comment by RamizAshurov** [comment]
1. Поменял размер кнопки
2. Здесь имеется ввиду, что попап не перекрывает хедр?
3. И в хедере, и в футере у кнопки "Заказать звонок" есть иконка

**Comment by foxhable** [comment]
1. Не поменял, все ещё 24х24

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/5548d4d4-315b-469d-b570-9f385240ef18)
</details> 


3. На мобилке её не должно быть. В заголовке проблемы написано, что это про мобилку - обращай внимание

<details><summary>Скрин макета</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/7dbf46d3-851f-4b1a-9450-c0fe8ee698bc)

</details>

**Comment by RamizAshurov** [comment]
- Поменял размер иконки
- Убрал иконку у кнопки
