### ISSUE TITLE
Ширина страницы

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#18]
Видимо во время загрузки из-за ширины шапки или чего-то другого выставляется неверная ширина документа и приходится отдалять. Попробуй через `overflow` скрыть горизонтальный скролл, исправит это проблему?

[load-bug.webm](https://github.com/aaccent/med-tourism/assets/36298346/8d514d49-ef65-445e-90a6-b165341d693d)

**Comment by RamizAshurov** [comment]
Проблема была в карте в футере, она вылезала за пределы. Исправил.
