### ISSUE TITLE
Заголовки

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#19]
На главной названия услуг сделай `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/e915f99f-a7d2-460c-a773-09da6b7a663d)
</details> 

---

Имена в отзывах сделай `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/c16a06ed-4113-4433-b158-b29539cd74ff)
</details> 

---

Вопросы сделай `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/98988ca9-697d-4454-8409-33af4032fc19)
</details> 

---

Названия клиник сделай `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/75723d2d-bf58-4233-95a6-6a6d4e8cafba)
</details> 

---

Названия услуг на странице проектов сделай `div`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/b41f00dc-a056-4dd2-a002-96a830924be0)
</details>

**Comment by RamizAshurov** [comment]
Исправил. На странице "Услуга" заменил заголовок на div

**Comment by foxhable** [comment]
- В выпадающем меню услуг замени `h*` теги на `div`
- На странице "Услуга" тэг заголовка "РЕАЛИЗОВАННЫЕ ПРОЕКТЫ" замени на `h2`
- "ОТВЕТИМ НА ВСЕ ВАШИ ВОПРОСЫ" `h2`

**Comment by RamizAshurov** [comment]
- Заменил заголовки в выпадающем меню
- На странице "Услуга" тэг заголовка "РЕАЛИЗОВАННЫЕ ПРОЕКТЫ" заменил на h2
- Всю строку "ОТВЕТИМ НА ВСЕ ВАШИ ВОПРОСЫ" заменил на  h2
