### ISSUE TITLE
Список услуг на главной

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#20]
Элементы `services-section__service-item` должны быть ссылками

![image](https://github.com/aaccent/med-tourism/assets/36298346/04b28aa9-7f98-4a6a-9197-2f0419e9c111)

**Comment by RamizAshurov** [comment]
Исправил.

**Comment by foxhable** [comment]
И тоже самое с реализованными проектами на странице "Услуга"

**Comment by RamizAshurov** [comment]
Исправил
