### ISSUE TITLE
Вопросы и ответы на мобилке

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#22]
1. Размер иконки открытия не тот. На макете иконка заполняет часть контейнера 24х24, а в верстке весь контейнер от края до края

<details><summary>Сравнение</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/87194b0c-d159-4822-a7fc-93fc11a7b5bb)
</details> 

---

2. Расстояния по бокам больше, чем в макете
3. Переносы в тексте вопроса не соответствуют макету
4. Мужик не по центру

**Comment by RamizAshurov** [comment]
1. Иконку исправил
2. Поправил боковые расстояния на мобилке. На десктопе вроде все по макету
3. Выставил переносы тегом br
4. Выровнял мужика
