### ISSUE TITLE
Разделительная полоса

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#23]
Между блоками на десктопе:
- Этапы
- Отзывы
- Наши клиенты
- Вопросы и ответы
- Сео блок

есть разделительная полоса

На мобилке она пропадает между "Этапы" и "Отзывы"

**Comment by RamizAshurov** [comment]
Расставил полосы.

**Comment by foxhable** [comment]
Между Сео блоком и Ответами на пк нету

**Comment by RamizAshurov** [comment]
Добавил полосу
