### ISSUE TITLE
Контент на мобилке

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#26]
1. Расстояния между блоками меньше, чем в макете

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/65ec95aa-9f4b-4a0e-97da-1f397b48f3fe)
</details> 

---

2. Размер текста цитаты и его автора должен быть `14px`
3. Расстояние после цитаты должно быть `20px`

**Comment by RamizAshurov** [comment]
1. Поправил расстояния
2. Уменьшил шрифт
3. Увеличил расстояние после цитаты
