### ISSUE TITLE
Блок "Директор компании" на мобилке

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#27]
1. Отступ сверху должен быть больше

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/45c257f7-27be-4916-8fee-3aed0363b3df)
</details> 

---

2. Расстояние после заголовка должно быть `20px`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/55698904-b693-478f-99df-54acef79e9df)
</details> 

---

3. Расстояние после блока должно быть больше

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/139d4d62-9601-4d9c-bd4b-79a2e23e80b2)
</details>

**Comment by RamizAshurov** [comment]
1. Поправил верхний отступ
2. Увеличил расстояние до заголовка
3. Увеличил расстояние после блока

**Comment by foxhable** [comment]
Расстояние после блока меньше, чем в макете

<details><summary>Сравнение</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/1cbdd7f6-b28d-46fe-8358-a6181aa5e97e)
</details>

**Comment by RamizAshurov** [comment]
![image](https://github.com/aaccent/med-tourism/assets/37570516/889187c1-1796-4195-885c-0eb2c3fe3a1b)
Проверил, на сайте стоит верный отступ

**Comment by foxhable** [comment]
А, ты смотришь на "О компании", я на "Страница услуга". В услуге неверный отступ, в компании ок

**Comment by RamizAshurov** [comment]
Исправил
