### ISSUE TITLE
Контакты на мобилке

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#28]
1. Расстояния между элементами должно быть `10px`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/dc5d1c10-b891-4916-89c3-19a1f4d1945a)
</details> 

---

2. Должно быть расстояние после блоков

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/60b26528-0b69-48c6-871f-cdf2db059dfb)
</details> 

---

3. Между заголовком и списком должно быть `20px`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/d995295a-786d-4f74-b595-8284995167fb)
</details>

**Comment by RamizAshurov** [comment]
Проверил все пункты, внес правки
