### ISSUE TITLE
Реализованные проекты

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#30]
- Под заголовком страницы должно быть `50px`
- Элементы должны быть ссылками, а не `article`
- Между рядами списка должно быть `100px`
- Под кнопкой "Все проекты" должно быть расстояние

**Comment by RamizAshurov** [comment]
1. Поправил отступ после заголовка
2. Сделал проекты ссылками на страницу "Услуга"
3. Увеличил отступ между рядами в сетке
4. Добаил отступ кнопке
