### ISSUE TITLE
Слайдеры

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#7]
1. На горизонтальных скроллбарах нет обводки
2. Если возможно, то нужно сделать пролистывание по скроллбару
3. "Назад" и "Далее" сделай через `button`, а не `div`

**Comment by RamizAshurov** [comment]
- Добавил обводку скроллбару
- Ползунок можно перелистовать
- Кнопки сделал buttton'ом

**Comment by foxhable** [comment]
Добавь на ползунок `cursor: pointer`. В "Наши клиенты" кнопки не `button`

**Comment by RamizAshurov** [comment]
Добавил курсор на ползунок. В "Наши клиенты" поменял тег на button

**Comment by foxhable** [comment]
Курсора нет

**Comment by RamizAshurov** [comment]
Исправил
