### ISSUE TITLE
Сео-блок

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#8]
1. Заголовок должен быть `h2`
2. "Читать полностью" кнопкой, которая разворачивает текст

**Comment by RamizAshurov** [comment]
1. Сделал заголовок h2

**Comment by RamizAshurov** [comment]
Кнопка "Читать полностью" работает

**Comment by foxhable** [comment]
Отступы пропали

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/3d20458c-00bf-4e95-b796-7928742d1d8a)
</details>
