### ISSUE TITLE
"РАБОТАЕМ В СООТВЕТСТВИИ С..."

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#9]
Заголовок должен быть `h2`

<details><summary>Скрин блока</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/4bb9266d-669c-4576-be2e-03346ec5c334)
</details> 

---

Иконка у кнопки "Читать подробнее" на мобилке не того размера

![image](https://github.com/aaccent/med-tourism/assets/36298346/2e95eede-a135-48a9-a870-bb8a79746ed1)

**Comment by RamizAshurov** [comment]
Поменял заголовок и иконку кнопки
